# Generated by Django 4.0.4 on 2022-05-28 08:54

from django.db import migrations, transaction
import pandas as pd
import os
from pathlib import Path
data_path = os.path.join(Path(__file__).parents[1], 'data')

def create_countries(apps, schema_editor):
    df = pd.read_csv(os.path.join(data_path, 'countries.csv'))
    Country = apps.get_model('recruit', 'Country')
    for record in df.to_dict('records'):
        with transaction.atomic():
            country = Country(**record)
            country.save()

def create_skills(apps, schema_editor):
    df = pd.read_csv(os.path.join(data_path, 'skills.csv'))
    Skill = apps.get_model('recruit', 'Skill')
    for record in df.to_dict('records'):
        with transaction.atomic():
            skill = Skill(**record)
            skill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_skill_aliases_skill_category_skill_domain_and_more'),
    ]

    operations = [
        migrations.RunPython(create_countries),
        migrations.RunPython(create_skills)
    ]
