# Generated by Django 4.0.4 on 2022-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20220528_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FULLFILlED', 'Fullfilled'), ('CANCELLED', 'Cancelled'), ('DRAFT', 'Draft')], default='OPEN', max_length=20),
        ),
    ]
