# Generated by Django 4.0.4 on 2022-05-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_job_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['code']},
        ),
    ]
