# Generated by Django 4.0.4 on 2022-05-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_jobskill_is_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['code'], 'verbose_name_plural': 'Countries'},
        ),
    ]
